### ISSUE TITLE
gitbook链接挂了？

### ISSUE THREAD

**Issue by biluohc** [xiaoweiChen/CMake-Cookbook#2]
会自动转到 https://chenxiaowei.gitbook.io/weighted-entropy-based-quantization/cmake-cookbook/

但还是 Page not found

**Comment by xiaoweiChen** [comment]
gitbook网站一直在做更新，这个跳转到的地址也是很迷了。
我更新了地址，点击就可以正常访问了。

**Comment by xiehao** [comment]
似乎新的又挂了，但原因不同。提示410错误：This space has been detected as spam and suspended

**Comment by xiaoweiChen** [comment]
@xiehao 登录的时候发现，账号被gitbook管理禁用了，“The user account has been disabled by an administrator.” 

要是github上看的不方便，用生成的离线PDF文件看吧。
