### ISSUE TITLE
关于第0章

### ISSUE THREAD

**Issue by ichdream** [xiaoweiChen/CMake-Cookbook#5]
第0章关于环境的配置，是中文版译者自己加进去的吗？
在英文版里没有找到。

**Comment by xiaoweiChen** [comment]
并不是，这本书我是花钱在亚马逊上买了电子版的。
我这有很多免费版本，或多或少的都有内容遗漏。
环境配置并不是本书重点，有了cmake的环境能将后续章节的东西运行起来就可以了。

**Comment by ichdream** [comment]
> 并不是，这本书我是花钱在亚马逊上买了电子版的。
> 我这有很多免费版本，或多或少的都有内容遗漏。
> 环境配置并不是本书重点，有了cmake的环境能将后续章节的东西运行起来就可以了。

了解，在第0章0.2 Docker镜像里面，有个命令“pipenv install --three” 这个是什么意思？
我尝试着运行，发现有错误，我猜测是要创建个单独的虚拟python 3环境吧，那是不是应该是“pipenv --three”
原谅我pipenv不是很熟悉，一般用conda pip 或者 自己改路径。

另外，我建议关于docker环境就不要用pienv管理了，感觉pipenv不是很方便，毕竟docker已经实现了环境隔离，可以一个docker一个python环境版本，这里直接用pip就好了。

最后，想表达下环境也很重要，环境配置好是地基，以免到后期做实验时出现错误，不好统一定位问题。

thanks。

**Comment by xiaoweiChen** [comment]
哈哈，理解你的困惑。这里没必要一定要使用pipenv进行操作，可以使用你更习惯的pip或conda install就好。也可以基于做的做好的docker，或自己做一个适合自己使用的docker。
因为这段的确是原书的内容，所以我也没想去修改，就直接粘出来，给大家看了。
原书中没有第0章，而是给了一些准备工作的介绍。我翻译的时候，为了方便整理，就将这些内容整合到了一个章节当中，命名为第0章。

**Comment by xiaoweiChen** [comment]
嗯，不同的人也有不同习惯，也许作者有很多Python环境，他用pipenv进行隔离管理。
你对pipenv不熟悉，也许别人有熟悉的，对吧。看该书的人应该不止你一人。
环境固然重要啦，但更重要的是对一些用法的理解。这样才能做到不管环境怎么变，你都能如何去做想做的事，并且出问题了，也知道问题在哪，对吧。

**Comment by ichdream** [comment]
> 哈哈，理解你的困惑。这里没必要一定要使用pipenv进行操作，可以使用你更习惯的pip或conda install就好。也可以基于做的做好的docker，或自己做一个适合自己使用的docker。
> 因为这段的确是原书的内容，所以我也没想去修改，就直接粘出来，给大家看了。
> 原书中没有第0章，而是给了一些准备工作的介绍。我翻译的时候，为了方便整理，就将这些内容整合到了一个章节当中，命名为第0章。

原来如此，感谢分享，赞一个👍
